# Generated by Django 5.2.17 on 2026-08-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("season", models.PositiveIntegerField(unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "Upcoming"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="UPCOMING",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-season"],
                "indexes": [
                    models.Index(
                        fields=["season"], name="tournaments_season_78bc24_idx"
                    ),
                    models.Index(
                        fields=["status"], name="tournaments_status_c3a7bb_idx"
                    ),
                ],
            },
        ),
    ]
