# Generated by Django 5.2.17 on 2026-08-10 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("venue", models.CharField(max_length=200)),
                ("match_number", models.PositiveIntegerField()),
                ("match_date", models.DateField()),
                ("match_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "Upcoming"),
                            ("LIVE", "Live"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="UPCOMING",
                        max_length=15,
                    ),
                ),
                ("team1_score", models.PositiveIntegerField(default=0)),
                ("team2_score", models.PositiveIntegerField(default=0)),
                ("result", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_matches",
                        to="teams.team",
                    ),
                ),
                (
                    "team2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="away_matches",
                        to="teams.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="won_matches",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["match_date", "match_time"],
                "indexes": [
                    models.Index(
                        fields=["match_date"], name="matches_mat_match_d_8426a6_idx"
                    ),
                    models.Index(
                        fields=["status"], name="matches_mat_status_a896a5_idx"
                    ),
                    models.Index(
                        fields=["tournament"], name="matches_mat_tournam_b0476d_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tournament", "match_number"),
                        name="unique_match_number_per_tournament",
                    )
                ],
            },
        ),
    ]
