# Generated by Django 5.2.17 on 2026-08-10 09:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("BATTER", "Batter"),
                            ("BOWLER", "Bowler"),
                            ("ALL_ROUNDER", "All Rounder"),
                            ("WICKET_KEEPER", "Wicket Keeper"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nationality", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("batting_style", models.CharField(blank=True, max_length=100)),
                ("bowling_style", models.CharField(blank=True, max_length=100)),
                (
                    "jersey_number",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="players/images/"
                    ),
                ),
                ("matches", models.PositiveIntegerField(default=0)),
                ("runs", models.PositiveIntegerField(default=0)),
                ("wickets", models.PositiveIntegerField(default=0)),
                (
                    "strike_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "batting_average",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "economy",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="players_pla_name_f5b1bf_idx"),
                    models.Index(
                        fields=["team"], name="players_pla_team_id_3b0f47_idx"
                    ),
                    models.Index(fields=["role"], name="players_pla_role_fe7c3e_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "jersey_number"),
                        name="unique_team_jersey_number",
                    )
                ],
            },
        ),
    ]
