# Generated by Django 5.2.17 on 2026-08-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("short_name", models.CharField(max_length=10, unique=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="teams/logos/"),
                ),
                ("captain", models.CharField(blank=True, max_length=150)),
                ("coach", models.CharField(blank=True, max_length=150)),
                ("home_ground", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="teams_team_name_43e047_idx"),
                    models.Index(
                        fields=["short_name"], name="teams_team_short_n_eadde9_idx"
                    ),
                ],
            },
        ),
    ]
