# Generated by Django 5.2.17 on 2026-08-10 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointsTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matches_played", models.PositiveIntegerField(default=0)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("no_results", models.PositiveIntegerField(default=0)),
                ("points", models.PositiveIntegerField(default=0)),
                (
                    "net_run_rate",
                    models.DecimalField(decimal_places=3, default=0, max_digits=6),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_table_entries",
                        to="teams.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_table_entries",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "indexes": [
                    models.Index(
                        fields=["tournament"], name="points_tabl_tournam_78af9a_idx"
                    ),
                    models.Index(
                        fields=["team"], name="points_tabl_team_id_3683ae_idx"
                    ),
                    models.Index(
                        fields=["points"], name="points_tabl_points_c7cfdd_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tournament", "team"),
                        name="unique_tournament_team_points",
                    )
                ],
            },
        ),
    ]
