# Generated by Django 5.2.17 on 2026-08-10 09:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PointsTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matches_played", models.PositiveIntegerField(default=0)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("no_results", models.PositiveIntegerField(default=0)),
                ("points", models.PositiveIntegerField(default=0)),
                (
                    "net_run_rate",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(-999)],
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_entries",
                        to="teams.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_table",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "indexes": [
                    models.Index(
                        fields=["tournament"], name="stats_point_tournam_404d3c_idx"
                    ),
                    models.Index(
                        fields=["team"], name="stats_point_team_id_aaa348_idx"
                    ),
                    models.Index(
                        fields=["position"], name="stats_point_positio_f28f47_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tournament", "team"),
                        name="unique_team_per_tournament_points",
                    )
                ],
            },
        ),
    ]
